PUT http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "jean2@gmail.com",
    "password": "fozejo45fzeij",
    "firstName": "Jean",
    "lastName": "Rakoto",
    "mobile_number": "8546541654685496"
}

###

GET http://192.168.173.160:8888/api/auth/verify/e8a51ff73ae0f464eac919de64e9280f4dc3af73

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "jean2@gmail.com",
    "password": "fozejo45fzeij"
}